name: Run (2026)

on:
  schedule:
  - cron: '0 7/6 * 10 *'
  - cron: '0 7/12 * 11 *'
  - cron: '0 * 3 10 *'    # day after 2025 round 1 close
  - cron: '0 * 24 10 *'   # day after 2025 round 2 close
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/run.yml
    secrets: inherit
    with:
      year: 2026
