name: Run

on:
  schedule:
  - cron: '0 7 * * *'
  - cron: '0 7/6 * 10 *'
  - cron: '0 7/12 * 11 *'
  - cron: '0 * 3 10 *'    # day after 2025 round 1 close
  - cron: '0 * 24 10 *'   # day after 2025 round 2 close
  workflow_dispatch:

jobs:
  run:
    strategy:
      matrix:
        client: [tba]
        year: [2025, 2026]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set env
      run: |
        echo "REGWATCH_BRANCH=data-${{matrix.year}}-${{matrix.client}}" >> "$GITHUB_ENV"
        echo "${{secrets.TBA_KEY}}" >> .tba.key
        git config user.name regwatch
        git config user.email regwatch
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Run script
      run: |
        uv run main.py \
          --year ${{matrix.year}} \
          --client ${{matrix.client}} \
          --target-repo-root . \
          --target-repo-branch "${REGWATCH_BRANCH}"
    - name: Push
      run: git push origin "${REGWATCH_BRANCH}"
